projects:
  Joker API:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: ap-northeast-1
        apiId: v5iffdx6argv5jovit4miqny64
        maxDepth: 2
extensions:
  amplify:
    version: 3
